version: '2'
services:
  customers-application:
    environment:
      - PORT0=8090
    image: customes-applications
    build:
      context: ./customers-applications
      dockerfile: Dockerfile
    ports:
      - 8090:8090

  customers-maint:
    environment:
      - PORT0=8091
    image: customers-maint
    build:
      context: ./customers-maint
      dockerfile: Dockerfile
    ports:
      - 8091:8091

  risk-person-contract:
    environment:
      - PORT0=8092
    image: risk-person-contract
    build:
      context: ./risk-person-contract
      dockerfile: Dockerfile
    ports:
      - 8092:8092
