/**
 * NOTE: This class is auto generated by the swagger code generator program (2.4.0-SNAPSHOT).
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */
package io.swagger.api;

import io.swagger.model.CheckEmployerResponse;
import io.swagger.model.Error;
import io.swagger.annotations.*;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestHeader;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.RequestPart;
import org.springframework.web.multipart.MultipartFile;

import javax.validation.Valid;
import javax.validation.constraints.*;
import java.util.List;
@javax.annotation.Generated(value = "io.swagger.codegen.languages.SpringCodegen", date = "2018-07-21T12:09:07.136+02:00")

@Api(value = "checkemployer", description = "the checkemployer API")
public interface CheckemployerApi {

    @ApiOperation(value = "Check Employee balcklist and Insolvency", nickname = "checkEmployer", notes = "Checks wether or not an employer is in a blacklist or insolvent", response = CheckEmployerResponse.class, tags={ "CheckEmployer", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "Check Employer Response", response = CheckEmployerResponse.class),
        @ApiResponse(code = 400, message = "Application error - Verify the BAWAG specific headers for detailed information"),
        @ApiResponse(code = 404, message = "Employer not found"),
        @ApiResponse(code = 200, message = "Unexpected error", response = Error.class) })
    @RequestMapping(value = "/checkemployer",
        produces = { "application/json" }, 
        consumes = { "application/json" },
        method = RequestMethod.POST)
    ResponseEntity<CheckEmployerResponse> checkEmployer(@ApiParam(value = "Register Number") @Valid @RequestParam(value = "registerNumber", required = false) String registerNumber,@ApiParam(value = "First Name") @Valid @RequestParam(value = "firstName", required = false) String firstName,@ApiParam(value = "companyName.surname") @Valid @RequestParam(value = "surname_companyName", required = false) String surnameCompanyName,@ApiParam(value = "birthdate FoundingDate") @Valid @RequestParam(value = "birthdate_foundingDate", required = false) String birthdateFoundingDate,@ApiParam(value = "Street ") @Valid @RequestParam(value = "street", required = false) String street,@ApiParam(value = "Postal code ") @Valid @RequestParam(value = "postalCode", required = false) String postalCode,@ApiParam(value = "OENBId ") @Valid @RequestParam(value = "oenbid", required = false) String oenbid,@ApiParam(value = "Phonetic search ") @Valid @RequestParam(value = "phoneticSearch", required = false) String phoneticSearch);

}
