/**
 * NOTE: This class is auto generated by the swagger code generator program (2.4.0-SNAPSHOT).
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */
package io.swagger.api;

import io.swagger.model.GrantingGuidelinesCorrectionRequest;
import io.swagger.model.GrantingGuidelinesCorrectionResponse;
import io.swagger.annotations.*;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestHeader;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.RequestPart;
import org.springframework.web.multipart.MultipartFile;

import javax.validation.Valid;
import javax.validation.constraints.*;
import java.util.List;
@javax.annotation.Generated(value = "io.swagger.codegen.languages.SpringCodegen", date = "2018-07-21T12:10:32.270+02:00")

@Api(value = "granting-guidelines-correction", description = "the granting-guidelines-correction API")
public interface GrantingGuidelinesCorrectionApi {

    @ApiOperation(value = "Granting Gudielines Correction", nickname = "grantingGuidelinesCorrection", notes = "Migrated from MCA Computes Available Income and Expenses based on the given data of the customer ", response = GrantingGuidelinesCorrectionResponse.class, tags={ "Granting Guidelines Correction", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "Success", response = GrantingGuidelinesCorrectionResponse.class),
        @ApiResponse(code = 400, message = "Application error - Verify the BAWAG specific headers for detailed information"),
        @ApiResponse(code = 404, message = "Account not found"),
        @ApiResponse(code = 200, message = "Unexpected error") })
    @RequestMapping(value = "/granting-guidelines-correction",
        produces = { "application/json" }, 
        method = RequestMethod.POST)
    ResponseEntity<GrantingGuidelinesCorrectionResponse> grantingGuidelinesCorrection(@ApiParam(value = "Granting Guidelines Correction Request" ,required=true )  @Valid @RequestBody GrantingGuidelinesCorrectionRequest wsRequest);

}
