/**
 * NOTE: This class is auto generated by the swagger code generator program (2.4.0-SNAPSHOT).
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */
package io.swagger.api;

import io.swagger.model.HouseholdCalculationCheck;
import io.swagger.model.HouseholdCalculationCheckResponse;
import io.swagger.annotations.*;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestHeader;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.RequestPart;
import org.springframework.web.multipart.MultipartFile;

import javax.validation.Valid;
import javax.validation.constraints.*;
import java.util.List;
@javax.annotation.Generated(value = "io.swagger.codegen.languages.SpringCodegen", date = "2018-07-21T12:10:32.270+02:00")

@Api(value = "householdcalculationCheck", description = "the householdcalculationCheck API")
public interface HouseholdcalculationCheckApi {

    @ApiOperation(value = "Risk-person data", nickname = "perfomHouseholdCheck", notes = "Input (manual and optional AISP calculation) Call to GrantingRules Service as well as AttachableIncome Service   Output migrated calculation ", response = HouseholdCalculationCheckResponse.class, tags={ "Household Calculation Checks", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "Success", response = HouseholdCalculationCheckResponse.class),
        @ApiResponse(code = 400, message = "Application error - Verify the BAWAG specific headers for detailed information"),
        @ApiResponse(code = 404, message = "Account not found"),
        @ApiResponse(code = 200, message = "Unexpected error") })
    @RequestMapping(value = "/householdcalculationCheck",
        produces = { "application/json" }, 
        method = RequestMethod.POST)
    ResponseEntity<HouseholdCalculationCheckResponse> perfomHouseholdCheck(@ApiParam(value = "HouseholdCalculationCheck Request" ,required=true )  @Valid @RequestBody HouseholdCalculationCheck wsRequest);

}
